# Generated by Django 5.0.4 on 2024-05-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RasterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=100)),
                ('north', models.DecimalField(decimal_places=3, max_digits=5)),
                ('south', models.DecimalField(decimal_places=3, max_digits=5)),
                ('west', models.DecimalField(decimal_places=3, max_digits=6)),
                ('east', models.DecimalField(decimal_places=3, max_digits=6)),
                ('spatial_resolution', models.CharField(choices=[('0.25', '0.25'), ('0.5', '0.5'), ('1', '1'), ('2', '2')], default='0.25', max_length=10)),
                ('spatial_agg_method', models.CharField(choices=[('mean', 'mean'), ('min', 'min'), ('max', 'max')], default='mean', max_length=10)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('temporal_resolution', models.CharField(choices=[('hour', 'hour'), ('day', 'day'), ('month', 'month'), ('year', 'year')], default='hour', max_length=10)),
                ('temporal_agg_method', models.CharField(choices=[('mean', 'mean'), ('min', 'min'), ('max', 'max')], default='mean', max_length=10)),
                ('session_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
